[build]
builder = "nixpacks"

[deploy]
startCommand = "python test_railway.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[services]]
name = "backend"
sourceDir = "backend" 